### ISSUE TITLE
any other way to create the render pipeline it's crashing the overlay window 

### ISSUE THREAD

**Issue by Shinobift** [ToxSylph/SeaOfChoros#16]
![image](https://user-images.githubusercontent.com/31035982/231277780-b955e0df-6316-43b0-9583-2308e6d1f9ed.png)

**Comment by ToxSylph** [comment]
There are many ways, but it needs to be refactored. If the crash occurs during injection, it is probably a problem with the ImGui library. If the DLL injects but at some point the overlay is not displayed, it is probably a bug in the render method when iterating through the list of actors.

**Comment by Shinobift** [comment]
Oh, it's crashing after sometime later I checked the render pipeline is not ok 
And great work and if you got time see the imdraw pipeline

can I get your discord?

**Comment by bwhaley7** [comment]
Did you find a fix to this? @Shinobift

**Comment by Shinobift** [comment]
@xSlapppz what fix?

**Comment by bwhaley7** [comment]
> @xSlapppz what fix?

Crashing from render pipeline. Was wondering if you refactored the code at all to fix this. I had no issues until I updated the hooking method to make it compatible with Win 11. Now I get overlay crashes. Was curious if you fixed this.

**Comment by Shinobift** [comment]
yes i fix that issue
maybe you getting crash bcoz of offset try to update
and if you want go for separate render method that also ok depends on how big was your present hook
and try to small down render think to identify the real cause of the crash
