### ISSUE TITLE
The resurrection time is quite long.

### ISSUE THREAD

**Issue by Astonish42** [ToxSylph/SeaOfChoros#6]
Is the swapchain is too old?

**Comment by ToxSylph** [comment]
This source has many performance issues. But the respawn times are more related to PC performance and especially hard drive, try to install the game on an SSD.

**Comment by Astonish42** [comment]
Yes, I installed the SSD and the graphics card was GTX3090. But it still stuck in the loading interface.
By the way, can you optimize the chain aiming and aim at the other two mast of gallon?
