### ISSUE TITLE
HookLib/HookLib.lib doesn't open issue

### ISSUE THREAD

**Issue by uhpep** [ToxSylph/SeaOfChoros#9]
![image](https://user-images.githubusercontent.com/89276433/208857606-d47c3cb2-f2c5-42bc-ae3b-0e9e8f221380.png)

any idea?

**Comment by Mitoxe113** [comment]
![image](https://user-images.githubusercontent.com/84990070/208959671-39b89b7a-ca99-4c3d-85ff-94f458d6de11.png)
you have to create a lib folder in root then 
![image](https://user-images.githubusercontent.com/84990070/208959758-41da9399-3278-4579-b9a9-af79f4aa5fcd.png)
Hooklib folder in  the lib folder and then put you lib files in there
like that
![image](https://user-images.githubusercontent.com/84990070/208959876-8614151b-3650-4371-b278-d6a8a6a16b68.png)
